<?php

/**
 * @file
 * classy_paragraphs_ui.module
 */

/**
 * Implements hook_menu().
 */
function classy_paragraphs_ui_menu() {
  $items['admin/config/content/classy-paragraphs-ui/%/edit'] = array(
   'title' => 'Classy Paragraphs UI ',
   'description' => 'Configuration for Classy Paragraphs',
   'page callback' => 'drupal_get_form',
   'page arguments' => array('classy_paragraphs_ui_edit', 4),
   'access arguments' => array('administer users'),

  );

  $items['admin/config/content/classy-paragraphs-ui/add'] = array(
    'title' => 'Add new class',
    'description' => 'Configuration for Classy Paragraphs',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('classy_paragraphs_ui_add'),
    'access arguments' => array('administer users'),
    'type' => MENU_LOCAL_ACTION,
  );
  $items['admin/config/content/classy-paragraphs-ui/%/delete'] = array(
   'title' => 'Classy Paragraphs UI ',
   'description' => 'Configuration for Classy Paragraphs',
   'page callback' => 'drupal_get_form',
   'page arguments' => array('classy_paragraphs_ui_delete',4),
   'access arguments' => array('administer users'),

  );

  $items['admin/config/content/classy-paragraphs-ui'] = array(
   'title' => 'Classy Paragraphs UI ',
   'description' => 'Configuration for Classy Paragraphs',
   'page callback' => 'classy_paragraphs_ui_list',
   'access arguments' => array('administer users'),
   'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}



/**
 * Edit form
 */
function classy_paragraphs_ui_edit($form, &$form_state, $the_id) {
  $form = array();

  $op = 'edit';
    $form = classy_paragraphs_ui_add_edit_form($form, $form_state, $the_id, $op);

 return $form;
}

/**
 * Add form
 */
function classy_paragraphs_ui_add($form, &$form_state) {
  $form = array();

  $the_id = '';

  $op = 'add';
  $form = classy_paragraphs_ui_add_edit_form($form, $form_state, $the_id, $op);

  return $form;
}

function classy_paragraphs_ui_delete($form, &$form_state, $the_id){

  $form = array();
  $form['#action'] = '?destination=admin/config/content/classy-paragraphs-ui';
  $form['the_id'] = array(
    '#type' => 'value',
    '#value' => $the_id,
  );


  return confirm_form(
    $form,
    t('Are you sure you want to delete this item?'),
    'admin/config/content/classy-paragraphs-ui',
    t('This action cannot be undone.'),
    t('Delete'),
    t('Cancel')
  );


  return $form;
}

function classy_paragraphs_ui_delete_submit($form, &$form_state) {

  $the_id = $form_state['values']['the_id'];

  $setting_array =variable_get('classy_paragraphs_settings');

  unset($setting_array[$the_id]);
  variable_set('classy_paragraphs_settings', $setting_array);

	drupal_set_message('You confirmed item ' . $form_state['values']['the_id'] . '.');
	$form_state['redirect'] = 'admin/config/content/classy-paragraphs-ui';
}

function classy_paragraphs_ui_edit_submit($form, &$form_state) {
  $the_id = $form_state['values']['the_id'];

  form_state_values_clean($form_state);

  //get the settings array
  $setting_array =variable_get('classy_paragraphs_settings');
  if(isset($the_id)){
    $setting_array[$the_id] = $form_state ['values'];
  }else{
    $setting_array[] = $form_state ['values'];
  }

  $classy_paragraphs_settings = $setting_array;
  variable_set('classy_paragraphs_settings', $classy_paragraphs_settings);
}

function classy_paragraphs_ui_add_submit($form, &$form_state) {

  form_state_values_clean($form_state);

  //get the settings array
  $setting_array =variable_get('classy_paragraphs_settings');

  $setting_array[] = $form_state ['values'];

  $classy_paragraphs_settings = $setting_array;
  variable_set('classy_paragraphs_settings', $classy_paragraphs_settings);

}

function classy_paragraphs_ui_list() {
  $out = '';
  $setting_array = variable_get('classy_paragraphs_settings');

  if(!empty($setting_array)) {
    $header = array('Name', 'Class', 'Edit', 'Delete');
    $rows = array();
    foreach ($setting_array as $key => $value) {
      $rows[] = array(
      $value['css_class_display'],
      $value['css_class_name'],
        '<a href="/admin/config/content/classy-paragraphs-ui/'. $key .'/edit">edit</a>',
        '<a href="/admin/config/content/classy-paragraphs-ui/'. $key .'/delete">delete</a>',
      );
    }

    $out .= theme('table', array('header' => $header, 'rows' => $rows));
  }

  return $out;
}

function classy_paragraphs_ui_add_edit_form($form, &$form_state, $the_id, $op){

  $setting_array =variable_get('classy_paragraphs_settings');

  $form = array();

  if ($op == 'edit'){
    $default_value = $setting_array[$the_id];
    $form['the_id'] = array(
      '#type' => 'value',
      '#value' => $the_id,
    );

  }else{
    $default_value = array('css_class_name'=>'','css_class_display'=>'');
  }


  /**
   * CSS class name
   */
  $form['css_class_name'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS Class name'),
    '#default_value' => $default_value['css_class_name'],
    '#size' => 16,
    '#maxlength' => 30,
    '#description' => t("The CSS class name you wish to add to a paragraph. Class names can contain only the characters [a-z0-9], hyphens (-) and underscores (_); they cannot start with a digit."),
    '#required' => TRUE,
  );

  /**
   * CSS Pretty or display class name
   */
  $form['css_class_display'] = array(
    '#type' => 'textfield',
    '#title' => t('CSS Pretty Name'),
    '#default_value' => $default_value['css_class_display'],
    '#size' => 16,
    '#maxlength' => 30,
    '#description' => t("The CSS class pretty name or display name, used for admin only."),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );
  $form['#action'] = '?destination=admin/config/content/classy-paragraphs-ui';
  return $form;
}

function classy_paragraphs_ui_classy_paragraphs_list_options_alter(&$options) {
  $setting_array =variable_get('classy_paragraphs_settings');

  foreach ($setting_array as $key => $value){
    $options[$value['css_class_name']] = t($value['css_class_display']);
  }
}
